build:
  image: ubuntu:20.04
  stage: build
  variables:
    DEBIAN_FRONTEND: noninteractive
    elixir_version: "1.13.4"
    MIX_ENV: test
  script:
    - |
      apt-get update
      apt-get install -y unzip curl git libssl-dev gzip libncurses5-dev ca-certificates gnupg2
      curl -fSL https://repo.uwucocoa.moe/pgp.key | apt-key add -
      echo "deb [arch=${arch}] https://repo.uwucocoa.moe/ stable main" | tee /etc/apt/sources.list.d/uwucocoa.list
      apt-get update -q -y
      apt-get install erlang-uwu
      mkdir -p ../Precompiled
      curl -fSL https://github.com/elixir-lang/elixir/releases/download/v${elixir_version}/Precompiled.zip -o ../Precompiled/Precompiled.zip
      pushd "../Precompiled" && unzip -o Precompiled.zip && popd
      export PATH="$(pwd)/../Precompiled/bin:${PATH}"
      mix local.hex --force
      mix local.rebar --force
      mix deps.get
      mix compile
      mix test --cover

