name: macos

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '.gitlab-ci.yml'
      - '.github/workflows/linux*'

jobs:
  mix_test:
    runs-on: macos-11
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Install Erlang and Elixir
        run: |
          brew install erlang elixir
          mix local.hex --force
          mix local.rebar --force

      - name: Compile and Test
        run: |
          mix deps.get
          mix test --cover
